### ISSUE TITLE
navigation limit reached

### ISSUE THREAD

**Issue by zkr6rc2iny** [Poofless321/chan-Sankaku-adblock#2]
Hello friend, even using the script I still receive the message = You have been flagged as using Ad-block, or scripts that meddle with the Ad-block detection methods in place. To continue using the site regularly, disable them, or upgrade to Sankaku Plus!  
there had to be a script Infinite Scroll you don't have to check if it is possible to do pls @Poofless321

**Comment by Poofless321** [comment]
Hi @zkr6rc2iny I  just updated the [sankaku_Redirect_blocker.js](sankaku_Redirect_blocker.js)  double check if it works

**Comment by zkr6rc2iny** [comment]
Still still receiving the message @Poofless321 
![27838375](https://github.com/Poofless321/chan-Sankaku-adblock/assets/138602857/8421745c-fd56-4cd5-8737-5a50cc757ba1)

**Comment by Poofless321** [comment]
@zkr6rc2iny Weird, it works fine for me. Are you sure you installed it correctly? You should make sure you copying the entire file and place it in an EMPTY new script

Double-check everything. If you want, you can PM me in Discord so that I can try to help you find the problem

poofless321#4396

**Comment by zkr6rc2iny** [comment]
so activated @Poofless321 
![81682782](https://github.com/Poofless321/chan-Sankaku-adblock/assets/138602857/5ad142fa-8bd7-4cdc-9ad2-5314b5be2cea)
